---
language: python
python:
  - "3.5"

branches:
  only:
    - "master"

install:
  - pip install flake8
  - pip install -e .

addons:
  postgresql: "9.4"

script:
  - flake8 constellation_forms
  - python manage.py test
