# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_forms', '0002_auto_20170331_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('-form_id', '-version'), 'permissions': (('form_owned_by', 'Form Owner'), ('form_visible', 'Form is Visible'))},
        ),
    ]
