# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_forms', '0003_apikey'),
        ('constellation_forms', '0003_auto_20170413_1604'),
    ]

    operations = [
    ]
