# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constellation_forms', '0004_merge_20170414_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='log_files/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellation_forms.FormSubmission')),
            ],
            options={
                'db_table': 'form_log',
                'ordering': ('-timestamp',),
            },
        ),
    ]
