# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_forms', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='mtype',
            field=models.IntegerField(default=1),
        ),
    ]
