# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_forms', '0006_log_mtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='log',
            name='file',
            field=models.FileField(upload_to='private/constellation_forms/log_files/'),
        ),
    ]
