# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_forms', '0007_auto_20170421_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
