# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_forms', '0007_auto_20170421_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validator',
        ),
    ]
